### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/component-tooltip#14]
**Is your feature request related to a problem? Please describe.**
It's not obvious the level of support provided for this repo, so let's add some clarification.

**Describe the solution you'd like**
- [x] add support level section and badge
- [ ] add license file and badge

**Describe alternatives you've considered**
n/a

**Comment by jeffpaul** [comment]
No license has been defined, so I'll hold off on adding a related license file and badge until that's confirmed.

**Comment by timwright12** [comment]
added MIT
