### ISSUE TITLE
Incorrect entry file in package.json

### ISSUE THREAD

**Issue by ivankruchkoff** [10up/component-tooltip#19]
**Describe the bug**
Incorrect entry file in JS, links to src, but should use transpiled version in dist.
https://github.com/10up/component-tooltip/blob/bc0d678/package.json#L6

Causing this issue in downstream dependencies: 10up/theme-scaffold#183

**Comment by timwright12** [comment]
hold off on this one

**Comment by nicholasio** [comment]
Addressed here: https://github.com/10up/component-library/pull/10
